### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by aissshah** [fac20/week9-AGIL#26]
File structure and variable names could have benefited from more planning for cohesiveness as there are a mix between different file and function names and structures. All the `.js` are in root. Could potentially be in a folder on its own. Additionally, there are duplicate files in both root and public. 

A small note, but styles.css could be tidier, i.e. * was in the middle of the file rather than close to the top.

Otherwise this is impressive code and it's a really pretty site!

**Comment by amberrignell** [comment]
Thanks for the tips :))
